fail_fast: true
exclude: |
  (?x)(
    \.snap$
  )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # Dogfooding
  - repo: https://github.com/lasuillard-s/devobs
    rev: main
    hooks:
      # Ensure each command has its test file pair
      - id: check-file-pair
        args:
          - --log-level
          - trace
          - --from=src/commands
          - --to=tests/commands
          - --include=*.rs
          - --expect={to}/{relative_from}/test_{filename}

  - repo: local
    hooks:
      - id: cargo-clippy
        name: cargo clippy
        language: system
        types: [rust]
        pass_filenames: false
        entry: cargo clippy
        args: [--fix, --allow-dirty, --, --deny, warnings]

      - id: cargo-fmt
        name: cargo fmt (nightly)
        language: system
        types: [rust]
        pass_filenames: false
        entry: rustup run nightly cargo fmt

      - id: cargo-nextest
        name: cargo nextest
        language: system
        types: [rust]
        pass_filenames: false
        entry: cargo nextest run
