# NOTE: We use pipx to run the devobs commands, otherwise it would require users
#       to install Rust toolchain and dependencies to build the project.
- id: devobs
  name: devobs
  description: Run devobs commands using pipx
  language: system
  entry: pipx run 'devobs~=0.1.0'

# Shortcuts for each command for convenience
- id: check-file-pair
  name: check-file-pair
  language: system
  entry: pipx run 'devobs~=0.1.0' check-file-pair
  # ? Example usage
  # args:
  #   - --from=src/commands
  #   - --to=tests/commands
  #   - --include='*.rs'
  #   - --expect='{to}/{relative_from}/test_{filename}'
  pass_filenames: false
